### ISSUE TITLE
Nearup stuck after restart (nearup stop + nearup run testnet)

### ISSUE THREAD

**Issue by tiagocmachado** [near/nearup#148]
```Oct 05 15:32:03.330  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 15:32:09.919  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"``` 

Nearup v0.6.2

**Comment by chefsale** [comment]
Can you please provide us with the logs from : ~/.nearup/logs folder?

**Comment by tiagocmachado** [comment]
Nearup.log:
```
2020-10-07 08:30:26.654 INFO tailer - show_logs: 5665|near|testnet
Oct 05 15:13:34.891  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 15:13:41.552  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"
Oct 05 15:16:01.003  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 15:16:07.646  INFO near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
Oct 05 15:20:39.332  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 15:20:45.928  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"
Oct 05 15:32:03.330  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 15:32:09.919  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"
Oct 05 15:41:58.153  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 15:42:04.704  INFO near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
Oct 05 15:49:30.316  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 15:49:36.956  INFO near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
Oct 05 16:22:12.945  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 16:22:19.606  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"
Oct 05 16:25:30.560  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 16:25:37.099  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"
Oct 05 16:33:04.692  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 16:33:11.290  INFO near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
Oct 05 19:40:15.090  INFO near: Version: 1.15.0-rc.1, Build: 0bd08ece-modified, Latest Protocol: 38
Oct 05 19:40:21.686  INFO near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
Oct 06 07:18:00.270  INFO near: Version: 1.16.0-beta.2, Build: 404bc6bf-modified, Latest Protocol: 39
Oct 06 07:18:06.929  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"
Oct 06 07:18:06.936  INFO near: Migrate DB from version 10 to 11
thread 'main' panicked at 'head must exist', core/store/src/migrations.rs:215:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  11: rust_begin_unwind
             at src/libstd/panicking.rs:385
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  13: core::option::expect_failed
             at src/libcore/option.rs:1264
  14: neard::apply_store_migrations
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 06 07:36:45.552  INFO near: Version: 1.16.0-rc.1, Build: 974d93dc-modified, Latest Protocol: 39
Oct 06 07:36:52.195  INFO near: Opening store database at "/home/ubuntu/.near/testnet/data"
Oct 06 07:36:52.206  INFO near: Migrate DB from version 10 to 11
thread 'main' panicked at 'head must exist', core/store/src/migrations.rs:215:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
2020-10-06 14:09:35.753 INFO nodelib - stop_native: Stopping process near with pid 4079...
2020-10-06 14:10:05.754 WARNING nodelib - stop_native: Timeout expired. Killing process 4079
2020-10-06 14:10:05.755 WARNING nodelib - stop_nearup: Stopping the nearup watcher...
2020-10-06 14:10:05.756 INFO watcher - stop_watcher: Stopping near watcher python3 with pid 1565...
2020-10-06 14:10:11.795 INFO nearup - run: Home directory is /home/ubuntu/.near/testnet...
2020-10-06 14:10:11.795 INFO nodelib - setup_and_run: Using officially compiled binary
2020-10-06 14:10:13.800 INFO util - download_binaries: Downloading latest deployed version for testnet
2020-10-06 14:10:13.801 INFO util - download_binaries: Downloading near to /home/ubuntu/.nearup/near/testnet/near from nearcore/Linux/1.16.0/974d93dc657f620d98de6589a2b5bc97be1db816/near...
2020-10-06 14:10:17.397 INFO util - download_binaries: Downloaded near to /home/ubuntu/.nearup/near/testnet/near...
2020-10-06 14:10:17.397 INFO util - download_binaries: Making the near executable...
2020-10-06 14:10:17.397 INFO util - download_binaries: Downloading genesis-csv-to-json to /home/ubuntu/.nearup/near/testnet/genesis-csv-to-json from nearcore/Linux/1.16.0/974d93dc657f620d98de6589a2b5bc97be1db816/genesis-csv-to-json...
2020-10-06 14:10:19.423 INFO util - download_binaries: Downloaded genesis-csv-to-json to /home/ubuntu/.nearup/near/testnet/genesis-csv-to-json...
2020-10-06 14:10:19.424 INFO util - download_binaries: Making the genesis-csv-to-json executable...
2020-10-06 14:10:34.606 INFO nodelib - genesis_changed: Remote genesis protocol version md5 9a361d2b96736cbd3b5965dccbdff20c, ours is b425fbae00f3a62d0a2ebe36e7004168
2020-10-06 14:10:34.607 INFO nodelib - check_and_update_genesis: Update genesis config and remove stale data for testnet
2020-10-06 14:11:13.982 INFO nodelib - print_staking_key: Stake for user 'stakin.pool.f863973.m0' with 'ed25519:GvddxjaxBCqGGB4kMNWNFtvozU1EEZ2jrnggKZW8LaU4'
2020-10-06 14:11:14.019 INFO nodelib - run: Node is running...
2020-10-06 14:11:14.019 INFO nodelib - run: To check logs call: `nearup logs` or `nearup logs --follow`
2020-10-06 14:11:14.019 INFO nodelib - run: Watcher is enabled. Starting watcher...
2020-10-06 14:11:14.019 INFO watcher - run_watcher: Starting the nearup watcher...
2020-10-06 14:11:20.726 INFO tailer - show_logs: 5569|near|testnet
2020-10-06 14:14:59.301 WARNING nodelib - stop_nearup: Stopping the near daemon...
2020-10-06 14:14:59.303 ERROR nodelib - stop_native: There was an error while stopping watcher: psutil.NoSuchProcess no process found with pid 5569
2020-10-06 14:14:59.303 WARNING nodelib - stop_nearup: Stopping the nearup watcher...
2020-10-06 14:14:59.304 INFO watcher - stop_watcher: Stopping near watcher python3 with pid 5570...
2020-10-06 14:15:03.881 INFO nearup - run: Home directory is /home/ubuntu/.near/testnet...
2020-10-06 14:15:03.881 INFO nodelib - setup_and_run: Using officially compiled binary
2020-10-06 14:15:05.943 INFO util - download_binaries: Downloading latest deployed version for testnet
2020-10-06 14:15:05.943 INFO util - download_binaries: Downloading near to /home/ubuntu/.nearup/near/testnet/near from nearcore/Linux/1.16.0/974d93dc657f620d98de6589a2b5bc97be1db816/near...
2020-10-06 14:15:09.136 INFO util - download_binaries: Downloaded near to /home/ubuntu/.nearup/near/testnet/near...
2020-10-06 14:15:09.136 INFO util - download_binaries: Making the near executable...
2020-10-06 14:15:09.137 INFO util - download_binaries: Downloading genesis-csv-to-json to /home/ubuntu/.nearup/near/testnet/genesis-csv-to-json from nearcore/Linux/1.16.0/974d93dc657f620d98de6589a2b5bc97be1db816/genesis-csv-to-json...
2020-10-06 14:15:11.273 INFO util - download_binaries: Downloaded genesis-csv-to-json to /home/ubuntu/.nearup/near/testnet/genesis-csv-to-json...
2020-10-06 14:15:11.273 INFO util - download_binaries: Making the genesis-csv-to-json executable...
2020-10-06 14:15:43.461 INFO nodelib - genesis_changed: The genesis version is up to date
2020-10-06 14:15:44.167 INFO nodelib - print_staking_key: Stake for user 'stakin.pool.f863973.m0' with 'ed25519:GvddxjaxBCqGGB4kMNWNFtvozU1EEZ2jrnggKZW8LaU4'
2020-10-06 14:15:44.201 INFO nodelib - run: Node is running...
2020-10-06 14:15:44.201 INFO nodelib - run: To check logs call: `nearup logs` or `nearup logs --follow`
2020-10-06 14:15:44.201 INFO nodelib - run: Watcher is enabled. Starting watcher...
2020-10-06 14:15:44.201 INFO watcher - run_watcher: Starting the nearup watcher...
2020-10-06 14:15:50.947 INFO tailer - show_logs: 5665|near|testnet
2020-10-06 14:16:27.633 INFO tailer - show_logs: 5665|near|testnet
2020-10-06 14:28:07.815 INFO tailer - show_logs: 5665|near|testnet
2020-10-06 21:18:53.854 INFO tailer - show_logs: 5665|near|testnet
2020-10-07 08:30:26.654 INFO tailer - show_logs: 5665|near|testnet
```

**Comment by tiagocmachado** [comment]
Testnet.log

```
^[[2mOct 06 07:36:45.552^[[0m ^[[32m INFO^[[0m near: Version: 1.16.0-rc.1, Build: 974d93dc-modified, Latest Protocol: 39
^[[2mOct 06 07:36:52.195^[[0m ^[[32m INFO^[[0m near: Opening store database at "/home/ubuntu/.near/testnet/data"
^[[2mOct 06 07:36:52.206^[[0m ^[[32m INFO^[[0m near: Migrate DB from version 10 to 11
thread 'main' panicked at 'head must exist', core/store/src/migrations.rs:215:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  11: rust_begin_unwind
             at src/libstd/panicking.rs:385
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  13: core::option::expect_failed
             at src/libcore/option.rs:1264
  14: neard::apply_store_migrations
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
^[[2mOct 06 14:11:14.080^[[0m ^[[32m INFO^[[0m near: Version: 1.16.0-rc.1, Build: 974d93dc-modified, Latest Protocol: 39
^[[2mOct 06 14:11:20.692^[[0m ^[[32m INFO^[[0m near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
^[[2mOct 06 14:15:44.223^[[0m ^[[32m INFO^[[0m near: Version: 1.16.0-rc.1, Build: 974d93dc-modified, Latest Protocol: 39
^[[2mOct 06 14:15:50.837^[[0m ^[[32m INFO^[[0m near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
```

**Comment by chefsale** [comment]
I believe you have to delete the ~/.near/testnet/data folder: `rm  -rf ~/.near/testnet/data folder` and retry.

**Comment by tiagocmachado** [comment]
Have done it several times and it ends with the same error

**Comment by chefsale** [comment]
Hmm, which command did you run to delete the folder and are you running on testnet or betanet?

**Comment by bowenwang1996** [comment]
looks like the data is corrupted somehow. You may need to delete data and resync

**Comment by tiagocmachado** [comment]
> Hmm, which command did you run to delete the folder and are you running on testnet or betanet?

Running on testnet. to delete folder I use rm -rf data/ calling it from inside .near/testnet/

**Comment by chefsale** [comment]
Can you run ls -al ~/.near/testnet just to verify that the data is deleted?

**Comment by tiagocmachado** [comment]
![Screenshot 2020-10-07 at 18 25 11](https://user-images.githubusercontent.com/30123077/95365909-9fa8fc00-08ca-11eb-947a-e41d8c1cf5a6.jpg)

**Comment by tiagocmachado** [comment]
Also already updated nearup to the lastest version(0.6.4) and the problem is the same

**Comment by chefsale** [comment]
@tiagocmachado what confuses me is that im not seeing the error in the logs anymore:
```
^[[2mOct 06 14:15:44.223^[[0m ^[[32m INFO^[[0m near: Version: 1.16.0-rc.1, Build: 974d93dc-modified, Latest Protocol: 39
^[[2mOct 06 14:15:50.837^[[0m ^[[32m INFO^[[0m near: Did not find "/home/ubuntu/.near/testnet/data" path, will be creating new store database
```
As you can see the other logs are from before,as we append the logs ot the same file.

I think you are fine once you deleted the data folder, you just need to give the node time to sync.

You can just see if the process is running with : `ps aux | grep near` and if yes, give it some time and run `nearup logs` to verify that its working, but I believe you fixed the issue, its just the logs are containing the old logs based on the time.

**Comment by tiagocmachado** [comment]
@chefsale started it 20min ago. I Will let it run until tomorrow and give you some feedback.
![Screenshot 2020-10-07 at 19 05 48](https://user-images.githubusercontent.com/30123077/95370119-388e4600-08d0-11eb-949d-0b38e022d475.jpg)

**Comment by chefsale** [comment]
@tiagocmachado if you can give me you validator name I can check for you what is the state of the node on the network?

**Comment by tiagocmachado** [comment]
> @tiagocmachado if you can give me you validator name I can check for you what is the state of the node on the network?

@chefsale stakin.pool.f863973.m0

**Comment by chefsale** [comment]
@tiagocmachado can you run for me:
```dmesg``` and ```ps aux | grep near``` and ```ps aux | grep watcher```

**Comment by tiagocmachado** [comment]
ps aux | grep near:
ubuntu    9536  0.0  0.5 116048 41556 ?        S    17:40   0:01 python3 /home/ubuntu/.local/bin/watcher run testnet /home/ubuntu/.near/testnet
ubuntu    9784  0.0  0.0  14656  1004 pts/1    S+   18:35   0:00 grep --color=auto near

ps aux | grep watcher:
ubuntu    9536  0.0  0.5 116048 41556 ?        S    17:40   0:01 python3 /home/ubuntu/.local/bin/watcher run testnet /home/ubuntu/.near/testnet
ubuntu    9786  0.0  0.0  14656  1108 pts/1    S+   18:36   0:00 grep --color=auto watcher

@chefsale

**Comment by tiagocmachado** [comment]
dmesg @chefsale 
![Screenshot 2020-10-07 at 19 40 51](https://user-images.githubusercontent.com/30123077/95373529-0b906200-08d5-11eb-8235-4f66c33d6020.jpg)

**Comment by chefsale** [comment]
Yes, I assumed this is the case, you are getting an our of memory error and the kernel kills you process. How much memory and cpu does you machine use? @bowenwang1996

**Comment by tiagocmachado** [comment]
@chefsale I'm running c4.xlarge on aws. the cpu utilization don't even get to 5%.
![Screenshot 2020-10-07 at 19 43 21](https://user-images.githubusercontent.com/30123077/95373803-688c1800-08d5-11eb-9bcc-ab185accf4b2.jpg)

**Comment by chefsale** [comment]
It is not a cpu issue, but a memory one.

**Comment by tiagocmachado** [comment]
should I increase? it runs with 7.5 GiB

![Screenshot 2020-10-07 at 19 47 47](https://user-images.githubusercontent.com/30123077/95374276-0bdd2d00-08d6-11eb-8cac-427b4dbff238.jpg)

**Comment by chefsale** [comment]
Yes, please use 16GB of RAM

**Comment by tiagocmachado** [comment]
back to life!

![Screenshot 2020-10-07 at 20 07 54](https://user-images.githubusercontent.com/30123077/95376306-d259f100-08d8-11eb-87ee-16495a89cbba.jpg)

Sorry I didn't had updated the testnet to the new hardware requirements. I think you can close the issue.
Thank you @chefsale

**Comment by chefsale** [comment]
No worries :)
