### ISSUE TITLE
 nearup run testnet - genesis file not found

### ISSUE THREAD

**Issue by pankajy721** [near/nearup#168]
I am learning near blockchain. After installation of all dependencies when i am trying to run testnet on ubuntu server i am encountering following error about genesis file
**FileNotFoundError: [Errno 2] No such file or directory: '/root/.near/testnet/genesis.json'**

Logs trace is as below :

2021-02-10 14:20:51.015 INFO nearup - run: Home directory is /root/.near/testnet...
2021-02-10 14:20:51.015 INFO nodelib - setup_and_run: Using officially compiled binary
2021-02-10 14:20:52.148 INFO util - download_binaries: Downloading latest deployed version for testnet
2021-02-10 14:20:52.148 INFO util - download_binaries: Downloading neard to /root/.nearup/near/testnet/neard from nearcore/Linux/1.18.0/0b0af075ac1f2828f51bb058a679b4209f541415/neard...
2021-02-10 14:20:54.383 INFO util - download_binaries: Downloaded neard to /root/.nearup/near/testnet/neard...
2021-02-10 14:20:54.383 INFO util - download_binaries: Making the neard executable...
Traceback (most recent call last):
  File "/root/.local/bin/nearup", line 155, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/bin/nearup", line 109, in run
    watcher=not no_watcher)
  File "/root/.local/lib/python3.6/site-packages/nearuplib/nodelib.py", line 253, in setup_and_run
    check_and_setup(binary_path, home_dir, init_flags)
  File "/root/.local/lib/python3.6/site-packages/nearuplib/nodelib.py", line 84, in check_and_setup
    with open(os.path.join(home_dir, 'genesis.json')) as genesis_fd:
**FileNotFoundError: [Errno 2] No such file or directory: '/root/.near/testnet/genesis.json'**

Is the genesis file available at the location ?

Any help is much appreciated.

**Comment by chefsale** [comment]
@pankajy721
