### ISSUE TITLE
./start.sh run testnet

### ISSUE THREAD

**Issue by pankajy721** [near/nearup#169]
I am trying to run NEAR testnet network on ubuntu machine.
Installed all dependencies and cloning of github project @ https://github.com/near/nearup.git

On running command ./start.sh run testnet, i see node is running but watchers are not running

Logs is as below 
2021-02-10 16:20:22.174 INFO nearup - run: Home directory is /root/.near/testnet...
2021-02-10 16:20:22.174 INFO nodelib - setup_and_run: Using officially compiled binary
2021-02-10 16:20:23.235 INFO util - download_binaries: Downloading latest deployed version for testnet
2021-02-10 16:20:23.236 INFO util - download_binaries: Downloading neard to /root/.nearup/near/testnet/neard from nearcore/Linux/1.18.0/0b0af075ac1f2828f51bb058a679b4209f541415/neard...
2021-02-10 16:20:29.952 INFO util - download_binaries: Downloaded neard to /root/.nearup/near/testnet/neard...
2021-02-10 16:20:29.952 INFO util - download_binaries: Making the neard executable...
2021-02-10 16:20:50.844 INFO nodelib - genesis_changed: The genesis version is up to date
2021-02-10 16:20:53.022 INFO nodelib - run: Node is running...
2021-02-10 16:20:53.023 INFO nodelib - run: To check logs call: `nearup logs` or `nearup logs --follow`
2021-02-10 16:20:53.023 INFO nodelib - run: Watcher is enabled. Starting watcher...
2021-02-10 16:20:53.023 INFO watcher - run_watcher: Starting the nearup watcher...

Also i see logs errors regarding TRust-DNS

Feb 10 16:20:53.026  INFO near: Version: 1.18.0-rc.3, Build: 0b0af075-modified, Latest Protocol: 42
Feb 10 16:21:13.550  INFO near: Opening store database at "/root/.near/testnet/data"
Feb 10 16:21:41.107  INFO stats: Server listening at <hash>@0.0.0.0:24567
Feb 10 16:21:41.401  WARN actix::actors::resolver: Can not create system dns resolver: io error: Error parsing resolv.conf: InvalidOption(3)
Feb 10 16:21:51.403  INFO stats: #24975852 Waiting for peers   0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 0 B
**Feb 10 16:21:51.404 ERROR actix_tls::connect: TRust-DNS can not load system config: Error parsing resolv.conf: InvalidOption(3)
Feb 10 16:21:52.405  INFO telemetry: Telemetry data could not be sent due to: Failed to connect to host: Timeout while establishing connection**

Please help me resolving this issue.

**Comment by bowenwang1996** [comment]
> Feb 10 16:21:41.401 WARN actix::actors::resolver: Can not create system dns resolver: io error: Error parsing resolv.conf: InvalidOption(3)

@frol do you know what this is about?

**Comment by pankajy721** [comment]
I am having similar issue when running MainNet node on a Docker container using nearup protocol latest image

Feb 10 17:59:38.383  INFO near: Version: 1.17.0, Build: 02396e9d, Latest Protocol: 41
Feb 10 17:59:38.387  INFO near: Did not find "/root/.near/mainnet/data" path, will be creating new store database
Feb 10 17:59:39.034  INFO stats: Server listening at ed25519:8DQ3WghJsYMpqGxB6TqeP1NWBFBoncz2BcPUpFwdugcr@0.0.0.0:24567
Feb 10 17:59:39.034  WARN actix::actors::resolver: Can not create system dns resolver: io error
Feb 10 17:59:49.037  INFO stats: # 9820210 Waiting for peers   0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 0 B
Feb 10 17:59:49.037 ERROR actix_connect: TRust-DNS can not load system config: Error parsing resolv.conf: InvalidOption(3)


Following are the logs for failing to start Watcher

2021-02-10 17:59:38.378 INFO watcher - run_watcher: Starting the nearup watcher...
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/nearuplib/exceptions.py", line 14, in wrapped
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/nearuplib/util.py", line 33, in read_from_s3
    response = s3_client.get_object(Bucket=S3_BUCKET, Key=path)
  File "/root/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.local/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/bin/watcher", line 81, in <module>
    main()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/bin/watcher", line 53, in run
    current_genesis_md5sum = latest_genesis_md5sum(network)
  File "/root/.local/lib/python3.6/site-packages/nearuplib/util.py", line 115, in latest_genesis_md5sum
    return read_from_s3(f'nearcore-deploy/{net}/genesis_md5sum').strip()
  File "/root/.local/lib/python3.6/site-packages/nearuplib/exceptions.py", line 16, in wrapped
    raise exception() from ex
nearuplib.exceptions.NetworkError

**Comment by frol** [comment]
@pankajy721 I have been running nearcore on various machines, but it is the first time I see such an error. What is the exact version of Ubuntu is that? Is it a fresh installation/cloud? When you run it inside Docker, what is the host OS?

**Comment by pankajy721** [comment]
Version is as follows 

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

Host machine is on Azure cloud

**Comment by frol** [comment]
@pankajy721 weird... It should be fine. Could you share the content of `/etc/resolv.conf`? Try replacing it with the following content:

```
nameserver 8.8.8.8
```

I don't think we will have the capacity to work on this issue any time soon unless someone investigates the reason and there is a clear way to patch it.

**Comment by pankajy721** [comment]
this change seemingly is not helping, issue remain the same. With the changes you have mentioned i see node startup is halted at genesis file download.

Please let me know if i can provide any further details which could help in investigation

**Comment by frol** [comment]
Testnet genesis is a few gigabytes in size, so let it do the job (it is not halted, but rather does not provide useful progress reporting)
