### ISSUE TITLE
Genesis file is not downloaded again after failing

### ISSUE THREAD

**Issue by m1cm1c** [near/nearup#176]
For some reason, the download of the genesis file failed when I first ran `nearup run testnet`:

```
$ nearup run testnet
2021-05-31 16:34:49.524 INFO nearup - run: Home directory is /home/christoph/.near/testnet...
2021-05-31 16:34:49.524 INFO nodelib - setup_and_run: Using officially compiled binary
2021-05-31 16:34:51.936 INFO util - download_binaries: Downloading latest deployed version for testnet
2021-05-31 16:34:51.936 INFO util - download_binaries: Downloading neard to /home/christoph/.nearup/near/testnet/neard from nearcore/Linux/1.19.0/daf13ddfa7341883f4c8eb00b063a98757dc59c8/neard...
2021-05-31 16:35:06.985 INFO util - download_binaries: Downloaded neard to /home/christoph/.nearup/near/testnet/neard...
2021-05-31 16:35:06.985 INFO util - download_binaries: Making the neard executable...
2021-05-31 16:35:06.985 INFO nodelib - check_and_setup: Setting up network configuration.
2021-05-31 16:35:06.985 INFO nodelib - init_near: Initializing the node configuration using near binary...
May 31 16:35:06.996  INFO near: Version: 1.19.0-rc.2, Build: daf13ddf, Latest Protocol: 45
May 31 16:35:06.996  INFO near: Downloading genesis file from: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/genesis.json ...
thread 'main' panicked at 'Unable to download the genesis file: Timeout', neard/src/config.rs:1034:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/christoph/.local/bin/nearup", line 155, in <module>
    cli()
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/christoph/.local/bin/nearup", line 103, in run
    setup_and_run(binary_path,
  File "/home/christoph/.local/lib/python3.9/site-packages/nearuplib/nodelib.py", line 251, in setup_and_run
    check_and_setup(binary_path, home_dir, init_flags)
  File "/home/christoph/.local/lib/python3.9/site-packages/nearuplib/nodelib.py", line 103, in check_and_setup
    init_near(home_dir, binary_path, chain_id, init_flags)
  File "/home/christoph/.local/lib/python3.9/site-packages/nearuplib/nodelib.py", line 34, in init_near
    subprocess.check_call(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/christoph/.nearup/near/testnet/neard', '--home=/home/christoph/.near/testnet', 'init', '--chain-id=testnet', '--download-genesis']' returned non-zero exit status 101.
```

Because I was able to access the URL in my browser, I simply re-ran the command. However, this lead to an error message about the gensis file missing:

```
$ nearup run testnet
2021-05-31 16:36:28.870 INFO nearup - run: Home directory is /home/christoph/.near/testnet...
2021-05-31 16:36:28.870 INFO nodelib - setup_and_run: Using officially compiled binary
2021-05-31 16:36:31.388 INFO util - download_binaries: Downloading latest deployed version for testnet
2021-05-31 16:36:31.388 INFO util - download_binaries: Downloading neard to /home/christoph/.nearup/near/testnet/neard from nearcore/Linux/1.19.0/daf13ddfa7341883f4c8eb00b063a98757dc59c8/neard...
2021-05-31 16:36:43.396 INFO util - download_binaries: Downloaded neard to /home/christoph/.nearup/near/testnet/neard...
2021-05-31 16:36:43.396 INFO util - download_binaries: Making the neard executable...
Traceback (most recent call last):
  File "/home/christoph/.local/bin/nearup", line 155, in <module>
    cli()
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/christoph/.local/lib/python3.9/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/christoph/.local/bin/nearup", line 103, in run
    setup_and_run(binary_path,
  File "/home/christoph/.local/lib/python3.9/site-packages/nearuplib/nodelib.py", line 251, in setup_and_run
    check_and_setup(binary_path, home_dir, init_flags)
  File "/home/christoph/.local/lib/python3.9/site-packages/nearuplib/nodelib.py", line 84, in check_and_setup
    with open(os.path.join(home_dir, 'genesis.json')) as genesis_fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/christoph/.near/testnet/genesis.json'
```

I think that it'd be better simply to delete an empty `~/.near/networkname` directory and continue as usual, instead of crashing.

**Comment by bowenwang1996** [comment]
@chefsale could you take a look?

**Comment by chefsale** [comment]
Missed it, will take a look.

**Comment by m1cm1c** [comment]
[some activity]
