### ISSUE TITLE
nearuplib.exceptions.NetworkError after nearup run testnet

### ISSUE THREAD

**Issue by sicmundu** [near/nearup#187]
Today I restarted the testnet node and now it gives an error:

```
2021-11-29 20:50:47.574 INFO nearup - run: Home directory is /root/.near/testnet...
2021-11-29 20:50:47.574 INFO nodelib - setup_and_run: Using officially compiled binary
2021-11-29 20:50:49.953 INFO util - download_binaries: Downloading latest deployed version for testnet
2021-11-29 20:50:49.953 INFO util - download_binaries: Downloading neard to /root/.nearup/near/testnet/neard from nearcore/Linux/1.23.0/af83ad25be1d24300f91364786e6f6992b28df18/neard...
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/nearuplib/exceptions.py", line 16, in wrapped
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/nearuplib/util.py", line 16, in download_from_s3
    s3_client.download_file(bucket, path, filepath)
  File "/root/.local/lib/python3.8/site-packages/boto3/s3/inject.py", line 171, in download_file
    return transfer.download_file(
  File "/root/.local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/root/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/root/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/root/.local/lib/python3.8/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/s3transfer/download.py", line 340, in _submit
    response = client.head_object(
  File "/root/.local/lib/python3.8/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.local/lib/python3.8/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/bin/nearup", line 156, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/bin/nearup", line 104, in run
    setup_and_run(binary_path,
  File "/root/.local/lib/python3.8/site-packages/nearuplib/nodelib.py", line 244, in setup_and_run
    download_binaries(chain_id, uname, chain_id == 'betanet')
  File "/root/.local/lib/python3.8/site-packages/nearuplib/util.py", line 81, in download_binaries
    download_from_s3(S3_BUCKETS['default'], download_url, download_path)
  File "/root/.local/lib/python3.8/site-packages/nearuplib/exceptions.py", line 18, in wrapped
    raise exception() from ex
nearuplib.exceptions.NetworkError
```

I tried reinstalling nearup but that didn't fix the error. I also noticed in the log that the network is chosen like this: `chain_id == 'betanet'`

**Comment by sicmundu** [comment]
Issue solved.

**Comment by francofadini** [comment]
> Issue solved.

How?
