### ISSUE TITLE
Does not show KeyboardInterrupt when Ctrl-c to exist a binary node

### ISSUE THREAD

**Issue by ailisp** [near/nearup#19]
It currently shows:
```
Apr 02 11:18:21.283  INFO stats: # 1265786 Downloading blocks 99% -/4  8/8/40 peers ⬇ 411.5kiB/s ⬆ 22.0kiB/s 5.00 bps 0 gas/s CPU: 89%, Mem: 74.2 MiB    
Apr 02 11:18:31.319  INFO stats: # 1265841 Downloading blocks 99% -/4  8/8/40 peers ⬇ 409.9kiB/s ⬆ 21.2kiB/s 5.58 bps 0 gas/s CPU: 89%, Mem: 77.1 MiB  
^CTraceback (most recent call last):
  File "/home/bo/.nearup/nearup", line 23, in <module>
    subprocess.run(args)
  File "/usr/lib/python3.7/subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 931, in communicate
    self.wait()
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
````

**Comment by ailisp** [comment]
Fixed in #30
