### ISSUE TITLE
MacOS nodocker fails with 403

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearup#6]
> nearup betanet --nodocker

Sorry your Operating System does not have officially compiled binary now, please compile nearcore locally and set --binary-path
Downloading latest deployed version for betanet
Traceback (most recent call last):
  File "/Users/cypress/.nearup/main.py", line 64, in <module>
    verbose=args.verbose)
  File "/Users/cypress/.nearup/nearuplib/nodelib.py", line 298, in setup_and_run
    download_binary(chain_id, uname)
  File "/Users/cypress/.nearup/nearuplib/nodelib.py", line 174, in download_binary
    f'https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/{uname}/{net_to_branch(net)}/{latest_deploy_version}/near', os.path.expanduser('~/.nearup/near/near'))
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by ailisp** [comment]
Made it not crash now. Mac OS build is on the plan but haven't setup yet
